### ISSUE TITLE
error when rosbag play example bag

### ISSUE THREAD

**Issue by agameplay** [Livox-SDK/livox_mapping#1]
env:ubuntu18.04
when use the readme.md's example,such as the follow:
```
roslaunch livox_mapping mapping_mid.launch
rosbag play YOUR_DOWNLOADED.bag
```
the rviz show only one frame, then it nochange,the ros master log show as the follow:
```
[rosmaster.master][INFO] 2020-07-28 11:16:32,758: -SUB [/livox/lidar] /scanRegistration http://parallels-Parallels-Virtual-Platform:37193/
[rosmaster.master][INFO] 2020-07-28 11:16:32,758: publisherUpdate[/rosout] -> http://parallels-Parallels-Virtual-Platform:40921/ ['http://parallels-Parallels-Virtual-Platform:45147/', 'http://parallels-Parallels-Virtual-Platform:34581/', 'http://parallels-Parallels-Virtual-Platform:35667/']: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2020-07-28 11:16:32,759: publisherUpdate[/livox_cloud] -> http://parallels-Parallels-Virtual-Platform:34581/ []
[rosmaster.master][INFO] 2020-07-28 11:16:32,760: publisherUpdate[/livox_cloud] -> http://parallels-Parallels-Virtual-Platform:34581/ []: sec=0.00, exception=[Errno 111] Connection refused
[rosmaster.master][INFO] 2020-07-28 11:16:32,760: -SERVICE [/scanRegistration/get_loggers] /scanRegistration rosrpc://parallels-Parallels-Virtual-Platform:47063
[rosmaster.master][INFO] 2020-07-28 11:16:32,762: -SERVICE [/scanRegistration/set_logger_level] /scanRegistration rosrpc://parallels-Parallels-Virtual-Platform:47063
[rosmaster.threadpool][ERROR] 2020-07-28 11:16:32,763: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 833, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rosmaster.master][INFO] 2020-07-28 11:16:32,763: publisherUpdate[/laser_cloud_sharp] -> http://parallels-Parallels-Virtual-Platform:34581/ []
[rosmaster.master][INFO] 2020-07-28 11:16:32,763: publisherUpdate[/laser_cloud_sharp] -> http://parallels-Parallels-Virtual-Platform:34581/ []: sec=0.00, exception=[Errno 111] Connection refused
[rosmaster.threadpool][ERROR] 2020-07-28 11:16:32,764: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 833, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rosmaster.master][INFO] 2020-07-28 11:16:32,764: publisherUpdate[/laser_cloud_flat] -> http://parallels-Parallels-Virtual-Platform:34581/ []
[rosmaster.master][INFO] 2020-07-28 11:16:32,764: publisherUpdate[/laser_cloud_flat] -> http://parallels-Parallels-Virtual-Platform:34581/ []: sec=0.00, exception=[Errno 111] Connection refused
[rosmaster.threadpool][ERROR] 2020-07-28 11:16:32,765: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 833, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rosmaster.master][INFO] 2020-07-28 11:16:32,795: -PUB [/rosout] /rviz http://parallels-Parallels-Virtual-Platform:45147/
```
And the rviz show this error:
`For frame [aft_mapped]: Fixed Frame [camera_init] does not exist`
how can i resove this problem?

**Comment by agameplay** [comment]
I can run livox_high_precision_mapping

**Comment by Livox-SDK** [comment]
What's the output info in terminal?
Check whether the bag file corresponds to the launch file.

**Comment by hessihan** [comment]
I can't play the example bag either, with errors for each steps in livox_mapping launch terminal.
`[ERROR] [1600506739.609292100]: Error transforming odometry 'Odometry' from frame '/camera_init' to frame 'camera_init'
`

**Comment by agameplay** [comment]
Just use the Ubuntu 16.04 version is my solution.

**Comment by xhibix** [comment]
> I can't play the example bag either, with errors for each steps in livox_mapping launch terminal. `[ERROR] [1600506739.609292100]: Error transforming odometry 'Odometry' from frame '/camera_init' to frame 'camera_init' `

Have you solved it? I met the same issue.
